#!/bin/sh

# Set the background
[ -z "$1" ] && find $HOME/.config/wallpapers -type f | fzf | xargs -r $0 && exit
[ "$1" = "-R" ] && ~/.fehbg && exit

[ "$1" = "-R" ] && $HOME/.fehbg

feh --bg-fill "$1"
# wal -i "$1"
